language: node_js

node_js:
  - 4

env:
  global:
    secure: SdYno9vqyRNylAQV9ALnlrwVlXc3NMDhLA6sh8W/N+ffP6rrLtASveMH8w/rJtKbTweJF5Of4Se6ifcNAWyzSrQGBTn06XgU4PIrauRQP0ZnmkCjR8xdulLWFt76OcQ1VBWKL6my8lLKQAAf1yNco3oq/7C6OHrQhmUaY8XMv+TFPDiBVgFJzXxtkWAf1Dpic8UYP/N+OlIVoa+CncbjYfuCGiC5oMY4VCmFgI90SYFLlUpY0SARjeGTZCeEZ4/2LZQfv281VbNZBmUm8iMu8Aae739sEqS+lF588yfwuqmVFDxt+OPUFqFV+HcikicsLS1RaOzdehAAruB9H902tQ9UqqOcbt+S+Q75GDa6EQM+rTQXImpes2jAH3GrlQZ5ZCJRCwj4cv8hN8KyHPPwy6CRpSUIkzbFY/IOSRxrIF5lwrQEiHTdyBxDtTmewZlkAxI9P4df35fzFQ5LWDUAvSrkJ8Yc/qJhr/STOMfu9hz1At3Fxuh4An8cO7lCApKFvNBCnbV4YKf6VX4+X5vsQHW2nCudXSzVRkLSq6q+imCj9PN3A/MuxnBrUxxsXG2S2otDNv47HfZHWEzQLjBIAkJdRtBvfdiAHoZ1mLZsK7K30cdJXXxSm923SvI59xVioVfs25+mW5Xx7gPlq66qUTbuieI25Af0+FxGpgBj9hc=
