# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: '5'

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true

cache:
  - node_modules
  - test-boilerplate/node_modules
  - docs/node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm prune
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
